import { withSystem } from './db.ts';

/**
 * Metering ingest — v2 decision 6.
 *
 * Append-only and idempotent by an event_id the WORKER generates. That matters: workers retry after
 * network failures, and the alternative (control-plane-generated ids) makes a retry look like new
 * usage. Reconstructing device-seconds later from session timestamps does not survive crashed
 * sessions, queued time, or the gap between "reserved" and "actually running" — which is why this
 * exists in Phase 1 rather than whenever billing gets built.
 */

export type MeterKind = 'device_seconds' | 'artifact_bytes' | 'egress_bytes';

export interface MeterEvent {
  eventId: string;      // uuid, generated by the worker, stable across retries
  sessionId: string | null;
  deviceId: string | null;
  kind: MeterKind;
  quantity: number;
  occurredAt: Date;
}

export interface IngestResult {
  /** Newly written. */
  recorded: number;
  /** Already present under the same event id — a retry landing, which is the design working. */
  duplicates: number;
  /**
   * Refused: the event named no session, an unknown session, or a session whose device is not on
   * this host. Counted rather than folded into `duplicates`, because a worker billing work it did
   * not do is an incident and must not look like a successful retry.
   */
  rejected: number;
}

/**
 * Record worker-reported usage.
 *
 * `hostId` is the AUTHENTICATED host, and it is the whole authorisation story: the SQL side joins
 * each event through its session to a device and drops anything that does not live on this host.
 * Note what is missing from `MeterEvent` — there is no `orgId`. Who gets charged is derived from the
 * session inside the database, because a worker that can name the paying org can bill any org
 * (migration 008).
 */
export async function ingest(hostId: string, events: MeterEvent[]): Promise<IngestResult> {
  if (events.length === 0) return { recorded: 0, duplicates: 0, rejected: 0 };

  return withSystem(async (c) => {
    const { rows } = await c.query(
      `SELECT o_recorded AS recorded, o_rejected AS rejected
         FROM record_metering($1, $2::uuid[], $3::uuid[], $4::uuid[],
                              $5::text[], $6::numeric[], $7::timestamptz[])`,
      [
        hostId,
        events.map((e) => e.eventId),
        events.map((e) => e.sessionId),
        events.map((e) => e.deviceId),
        events.map((e) => e.kind),
        events.map((e) => e.quantity),
        events.map((e) => e.occurredAt),
      ],
    );
    const recorded = Number(rows[0].recorded);
    const rejected = Number(rows[0].rejected);
    return { recorded, rejected, duplicates: events.length - recorded - rejected };
  });
}

/** Usage rollup for a billing period. */
/**
 * `to` MAY BE NULL, AND NULL MEANS "NO UPPER BOUND".
 *
 * Not a default of `new Date()`. Every timestamp compared here is written by Postgres's `now()`,
 * and a bound computed from the API server's clock is a DIFFERENT clock — routinely a millisecond
 * or two behind, and free to be far worse across two machines. A row written just now then falls
 * outside its own window and is silently not counted. See the note on `GET /account/usage`.
 */
export async function usage(orgId: string, from: Date, to: Date | null) {
  return withSystem(async (c) => {
    const { rows } = await c.query(
      `SELECT kind, sum(quantity)::float8 AS total
         FROM metering_events
        WHERE org_id = $1 AND occurred_at >= $2
          AND ($3::timestamptz IS NULL OR occurred_at < $3)
        GROUP BY kind`,
      [orgId, from, to],
    );
    return Object.fromEntries(rows.map((r) => [r.kind, r.total])) as Partial<Record<MeterKind, number>>;
  });
}
