import { withSystem } from './db.ts';

/**
 * Metering ingest — v2 decision 6.
 *
 * Append-only and idempotent by an event_id the WORKER generates. That matters: workers retry after
 * network failures, and the alternative (control-plane-generated ids) makes a retry look like new
 * usage. Reconstructing device-seconds later from session timestamps does not survive crashed
 * sessions, queued time, or the gap between "reserved" and "actually running" — which is why this
 * exists in Phase 1 rather than whenever billing gets built.
 */

export type MeterKind = 'device_seconds' | 'artifact_bytes' | 'egress_bytes';

export interface MeterEvent {
  eventId: string;      // uuid, generated by the worker, stable across retries
  sessionId: string | null;
  deviceId: string | null;
  kind: MeterKind;
  quantity: number;
  occurredAt: Date;
}

export interface IngestResult {
  /** Newly written. */
  recorded: number;
  /** Already present under the same event id — a retry landing, which is the design working. */
  duplicates: number;
  /**
   * Refused: the event named no session, an unknown session, or a session whose device is not on
   * this host. Counted rather than folded into `duplicates`, because a worker billing work it did
   * not do is an incident and must not look like a successful retry.
   */
  rejected: number;
}

/**
 * Record worker-reported usage.
 *
 * `hostId` is the AUTHENTICATED host, and it is the whole authorisation story: the SQL side joins
 * each event through its session to a device and drops anything that does not live on this host.
 * Note what is missing from `MeterEvent` — there is no `orgId`. Who gets charged is derived from the
 * session inside the database, because a worker that can name the paying org can bill any org
 * (migration 008).
 */
export async function ingest(hostId: string, events: MeterEvent[]): Promise<IngestResult> {
  if (events.length === 0) return { recorded: 0, duplicates: 0, rejected: 0 };

  return withSystem(async (c) => {
    const { rows } = await c.query(
      `SELECT o_recorded AS recorded, o_rejected AS rejected
         FROM record_metering($1, $2::uuid[], $3::uuid[], $4::uuid[],
                              $5::text[], $6::numeric[], $7::timestamptz[])`,
      [
        hostId,
        events.map((e) => e.eventId),
        events.map((e) => e.sessionId),
        events.map((e) => e.deviceId),
        events.map((e) => e.kind),
        events.map((e) => e.quantity),
        events.map((e) => e.occurredAt),
      ],
    );
    const recorded = Number(rows[0].recorded);
    const rejected = Number(rows[0].rejected);
    return { recorded, rejected, duplicates: events.length - recorded - rejected };
  });
}

/** Usage rollup for a billing period. */
/**
 * `to` MAY BE NULL, AND NULL MEANS "NO UPPER BOUND".
 *
 * Not a default of `new Date()`. Every timestamp compared here is written by Postgres's `now()`,
 * and a bound computed from the API server's clock is a DIFFERENT clock — routinely a millisecond
 * or two behind, and free to be far worse across two machines. A row written just now then falls
 * outside its own window and is silently not counted. See the note on `GET /account/usage`.
 */
export async function usage(orgId: string, from: Date, to: Date | null) {
  return withSystem(async (c) => {
    const { rows } = await c.query(
      `SELECT kind, sum(quantity)::float8 AS total
         FROM metering_events
        WHERE org_id = $1 AND occurred_at >= $2
          AND ($3::timestamptz IS NULL OR occurred_at < $3)
        GROUP BY kind`,
      [orgId, from, to],
    );
    return Object.fromEntries(rows.map((r) => [r.kind, r.total])) as Partial<Record<MeterKind, number>>;
  });
}

export interface UsageDay {
  /** `YYYY-MM-DD`, UTC. */
  day: string;
  deviceSeconds: number;
  artifactBytes: number;
  egressBytes: number;
}

/**
 * The same numbers, by day.
 *
 * A SINGLE THIRTY-DAY TOTAL IS NOT A USAGE VIEW. "You used 41 device-hours" answers nothing anybody
 * acts on: whether that was a steady drip or one runaway suite on Tuesday is the entire question,
 * and the two are indistinguishable in a sum.
 *
 * BUCKETED IN UTC, deliberately and stated on the wire, because `occurred_at` is a UTC instant and
 * the alternative — bucketing in the server's local zone — makes the same data produce different
 * days depending on where the container runs. A console that wants local days can re-bucket; it
 * cannot un-bucket.
 *
 * DAYS WITH NO USAGE ARE ABSENT rather than zero-filled. Filling them here would mean inventing
 * rows for a window the caller chose, and a caller plotting a chart needs to decide for itself
 * whether a gap is a zero or the edge of its data.
 */
export async function usageByDay(orgId: string, from: Date, to: Date | null): Promise<UsageDay[]> {
  return withSystem(async (c) => {
    const { rows } = await c.query(
      `SELECT to_char(date_trunc('day', occurred_at AT TIME ZONE 'UTC'), 'YYYY-MM-DD') AS day,
              sum(quantity) FILTER (WHERE kind = 'device_seconds')::float8 AS device_seconds,
              sum(quantity) FILTER (WHERE kind = 'artifact_bytes')::float8 AS artifact_bytes,
              sum(quantity) FILTER (WHERE kind = 'egress_bytes')::float8   AS egress_bytes
         FROM metering_events
        WHERE org_id = $1 AND occurred_at >= $2
          AND ($3::timestamptz IS NULL OR occurred_at < $3)
        GROUP BY 1
        ORDER BY 1`,
      [orgId, from, to],
    );
    return rows.map((r) => ({
      day: r.day as string,
      deviceSeconds: Number(r.device_seconds ?? 0),
      artifactBytes: Number(r.artifact_bytes ?? 0),
      egressBytes: Number(r.egress_bytes ?? 0),
    }));
  });
}
