import { withSystem } from './db.ts';

/**
 * Metering ingest — v2 decision 6.
 *
 * Append-only and idempotent by an event_id the WORKER generates. That matters: workers retry after
 * network failures, and the alternative (control-plane-generated ids) makes a retry look like new
 * usage. Reconstructing device-seconds later from session timestamps does not survive crashed
 * sessions, queued time, or the gap between "reserved" and "actually running" — which is why this
 * exists in Phase 1 rather than whenever billing gets built.
 */

export type MeterKind = 'device_seconds' | 'artifact_bytes' | 'egress_bytes';

export interface MeterEvent {
  eventId: string;      // uuid, generated by the worker, stable across retries
  orgId: string;
  sessionId: string | null;
  deviceId: string | null;
  kind: MeterKind;
  quantity: number;
  occurredAt: Date;
}

/** Returns how many events were newly recorded. Duplicates are silently ignored, by design. */
export async function ingest(events: MeterEvent[]): Promise<number> {
  if (events.length === 0) return 0;

  return withSystem(async (c) => {
    const { rows } = await c.query(
      `INSERT INTO metering_events
         (event_id, org_id, session_id, device_id, kind, quantity, occurred_at)
       SELECT * FROM unnest(
         $1::uuid[], $2::uuid[], $3::uuid[], $4::uuid[], $5::text[], $6::numeric[], $7::timestamptz[]
       )
       ON CONFLICT (event_id) DO NOTHING
       RETURNING event_id`,
      [
        events.map((e) => e.eventId),
        events.map((e) => e.orgId),
        events.map((e) => e.sessionId),
        events.map((e) => e.deviceId),
        events.map((e) => e.kind),
        events.map((e) => e.quantity),
        events.map((e) => e.occurredAt),
      ],
    );
    return rows.length;
  });
}

/** Usage rollup for a billing period. */
export async function usage(orgId: string, from: Date, to: Date) {
  return withSystem(async (c) => {
    const { rows } = await c.query(
      `SELECT kind, sum(quantity)::float8 AS total
         FROM metering_events
        WHERE org_id = $1 AND occurred_at >= $2 AND occurred_at < $3
        GROUP BY kind`,
      [orgId, from, to],
    );
    return Object.fromEntries(rows.map((r) => [r.kind, r.total])) as Partial<Record<MeterKind, number>>;
  });
}
